application: blockchaindata
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /stylesheets
  static_dir: stylesheets

- url: /balances
  script: Blockchaindata.app

- url: /utxos
  script: Blockchaindata.app

- url: /transactions
  script: Blockchaindata.app

- url: /block
  script: Blockchaindata.app

- url: /latestBlock
  script: Blockchaindata.app

- url: /primeInputAddress
  script: Blockchaindata.app

- url: /
  script: Blockchaindata.app

- url: /documentation
  script: Blockchaindata.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: pycrypto
  version: "2.6"